import { cleanUrl, documentTypeOf, fetchJson, isoDate, truncate } from "../common";
import type { PrimarySourceAdapter, PrimarySourceResult } from "../types";

const ODS_API = "https://documents.un.org/api/search";
const ODS_WASM = "https://documents.un.org/static/wasm_v_bg.wasm";

interface OdsRecord {
  id?: string;
  symbol?: string;
  title?: string;
  publication_date?: string;
  subjects?: string[];
}

interface OdsResponse {
  status?: number;
  body?: { data?: OdsRecord[] };
}

interface OdsWasmExports {
  memory: WebAssembly.Memory;
  check: (year: bigint, month: bigint, day: bigint, hour: bigint, minute: bigint) => bigint;
  __wbindgen_start: () => void;
  __wbindgen_exn_store: (index: number) => void;
  __externref_table_alloc: () => number;
  __wbindgen_export_2: WebAssembly.Table;
  __wbindgen_malloc: (size: number, align: number) => number;
  __wbindgen_realloc: (ptr: number, oldSize: number, newSize: number, align: number) => number;
}

let wasmModule: Promise<WebAssembly.Module> | undefined;

function symbolFromQuery(query: string): string {
  const match = query.match(/\b(?:A|S|E|ST|TD|DP|HR|CR|CAT|JIU|UNEP|UNWTO)\.?\s*\/\s*[A-Z0-9-]+(?:\s*\/\s*[A-Z0-9-]+)*\b/i);
  return match?.[0].replace(/\s+/g, "").toUpperCase() ?? "";
}

function directResult(symbol: string): PrimarySourceResult {
  return {
    id: `un-ods:${symbol}`,
    title: `United Nations document ${symbol}`,
    institution: "United Nations / UN Official Document System",
    organization: "United Nations",
    country: "International organization",
    documentType: documentTypeOf(symbol, "Documents"),
    publicationDate: "",
    snippet: "Open the official United Nations document record.",
    url: `https://docs.un.org/en/${encodeURIComponent(symbol)}?direct=true`,
    sourceIdentifier: symbol,
  };
}

function odsImports(): {
  imports: { wbg: Record<string, (...args: any[]) => any> };
  setWasm: (exports: OdsWasmExports) => void;
} {
  // The ODS access token is generated by the official WebAssembly helper. The
  // helper only needs the official host, so no secret or browser session is
  // involved. Keeping this server-side prevents the token from reaching the UI.
  let wasm: OdsWasmExports;
  let bytes: Uint8Array | undefined;
  let byteLength = 0;
  const textEncoder = new TextEncoder();
  const textDecoder = new TextDecoder("utf-8", { ignoreBOM: true, fatal: true });

  const memoryBytes = () => new Uint8Array(wasm.memory.buffer);
  const writeString = (value: string): number => {
    const encoded = textEncoder.encode(value);
    const target = wasm.__wbindgen_malloc(encoded.length, 1) >>> 0;
    memoryBytes().subarray(target, target + encoded.length).set(encoded);
    byteLength = encoded.length;
    return target;
  };

  const readString = (ptr: number, length: number): string => {
    const view = bytes?.buffer === wasm.memory.buffer ? bytes : (bytes = memoryBytes());
    return textDecoder.decode(view.subarray(ptr >>> 0, (ptr >>> 0) + length));
  };

  const refs = () => wasm.__wbindgen_export_2;
  const storeRef = (value: unknown): number => {
    const index = wasm.__externref_table_alloc();
    refs().set(index, value);
    return index;
  };
  const safeCall = (fn: (...args: any[]) => any, args: IArguments | any[]) => {
    try {
      return fn(...Array.from(args));
    } catch (error) {
      wasm.__wbindgen_exn_store(storeRef(error));
      return undefined;
    }
  };

  const odsWindow = { location: { host: "documents.un.org" } };
  const imports: Record<string, (...args: any[]) => any> = {
    __wbg_call_672a4d21634d4a24: function () {
      return safeCall((fn, receiver) => fn.call(receiver), arguments);
    },
    __wbg_host_9bd7b5dc07c48606: function (out: number, location: { host: string }) {
      return safeCall(() => {
        const ptr = writeString(location.host);
        const view = new DataView(wasm.memory.buffer);
        view.setInt32(out + 4, byteLength, true);
        view.setInt32(out, ptr, true);
      }, arguments);
    },
    __wbg_instanceof_Window_def73ea0955fc569: (value: unknown) => Boolean(value),
    __wbg_location_350d99456c2f3693: (value: { location: unknown }) => value.location,
    __wbg_newnoargs_105ed471475aaf50: (ptr: number, length: number) => new Function(readString(ptr, length)),
    __wbg_static_accessor_GLOBAL_88a902d13a557d07: () => storeRef(odsWindow),
    __wbg_static_accessor_GLOBAL_THIS_56578be7e9f832b0: () => storeRef(odsWindow),
    __wbg_static_accessor_SELF_37c5d418e4bf5819: () => storeRef(odsWindow),
    __wbg_static_accessor_WINDOW_5de37043a91a9c40: () => storeRef(odsWindow),
    __wbindgen_debug_string: (out: number, value: unknown) => {
      const ptr = writeString(String(value));
      const view = new DataView(wasm.memory.buffer);
      view.setInt32(out + 4, byteLength, true);
      view.setInt32(out, ptr, true);
    },
    __wbindgen_init_externref_table: () => {
      const table = refs();
      const start = table.grow(4);
      table.set(0, undefined);
      table.set(start, undefined);
      table.set(start + 1, null);
      table.set(start + 2, true);
      table.set(start + 3, false);
    },
    __wbindgen_is_undefined: (value: unknown) => value === undefined,
    __wbindgen_throw: (ptr: number, length: number) => {
      throw new Error(readString(ptr, length));
    },
  };

  return {
    imports: { wbg: imports },
    setWasm: (exports) => {
      wasm = exports;
    },
  };
}

async function odsAccessToken(): Promise<string> {
  wasmModule ??= fetch(ODS_WASM, { headers: { accept: "application/wasm" } })
    .then((response) => {
      if (!response.ok) throw new Error(`ODS token helper returned ${response.status}.`);
      return response.arrayBuffer();
    })
    .then((buffer) => WebAssembly.compile(buffer));

  const module = await wasmModule;
  const bindings = odsImports();
  const instance = await WebAssembly.instantiate(module, bindings.imports);
  const wasm = instance.exports as unknown as OdsWasmExports;
  // The imports close over the exports during start-up; initialise the module
  // before asking it to calculate the current five-minute access token.
  bindings.setWasm(wasm);
  wasm.__wbindgen_start();
  const now = new Date();
  const token = wasm.check(
    BigInt(now.getUTCFullYear()),
    BigInt(now.getUTCMonth() + 1),
    BigInt(now.getUTCDate()),
    BigInt(now.getUTCHours()),
    BigInt(now.getUTCMinutes()),
  );
  return token.toString();
}

async function searchOds(query: string, signal?: AbortSignal): Promise<PrimarySourceResult[]> {
  const token = await odsAccessToken();
  const body = {
    symbol: "*",
    jobNumber: "",
    publicationDate: "* TO *",
    releaseDate: "* TO *",
    title: "",
    subject: "",
    session: "",
    agenda: "",
    truncation: "right",
    fullTextSearch: { language: "en", searchText: query, type: "Find this phrase", exact: false },
    sortOptions: { sortField: "Sort by relevance" },
    pagination: { currentPage: 1, itemsPerPage: 12 },
    screenLanguage: "en",
    tcodes: [],
  };
  const requestId = globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const payload = await fetchJson<OdsResponse>(`${ODS_API}?l=en&rid=${encodeURIComponent(requestId)}`, {
    method: "POST",
    signal,
    headers: {
      "content-type": "application/json",
      authorization: `Access ${token}`,
      "cache-control": "public, max-age=0",
    },
    body: JSON.stringify(body),
  });

  return (payload.body?.data ?? []).flatMap((record) => {
    const symbol = String(record.symbol ?? "").trim();
    const title = String(record.title ?? "").trim() || (symbol ? `United Nations document ${symbol}` : "");
    if (!title || !symbol) return [];
    const subjects = Array.isArray(record.subjects) ? record.subjects.filter(Boolean).join(", ") : "";
    const url = cleanUrl(`https://docs.un.org/en/${encodeURIComponent(symbol)}?direct=true`);
    return [{
      id: `un-ods:${record.id ?? symbol}`,
      title,
      institution: "United Nations / UN Official Document System",
      organization: "United Nations",
      country: "International organization",
      documentType: documentTypeOf(`${title} ${symbol}`, "Documents"),
      publicationDate: isoDate(record.publication_date),
      snippet: truncate(subjects || "Official United Nations document record."),
      url,
      sourceIdentifier: symbol,
    } satisfies PrimarySourceResult];
  });
}

export const unitedNations: PrimarySourceAdapter = {
  id: "un-ods",
  institution: "United Nations / UN Official Document System",
  organization: "United Nations",
  country: "International organization",
  async search({ query, signal }) {
    const symbol = symbolFromQuery(query);
    const direct = symbol ? [directResult(symbol)] : [];
    try {
      return [...direct, ...(await searchOds(query, signal))].slice(0, 12);
    } catch {
      // A direct document symbol remains useful even if the ODS search service
      // is temporarily unavailable or its anti-abuse layer changes.
      return direct;
    }
  },
};
